# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

